const types = {
  FETCH_MAILS_SUCCESS: 'FETCH_MAILS_SUCCESS',
  FETCH_MAILS_FURTHER_SUCCESS: 'FETCH_MAILS_FURTHER_SUCCESS',
  FETCH_FAILURE: 'FETCH_FAILURE',
  DELETE_MAILS: 'DELETE_MAILS',
  CHANGE_MAIL_STATUS: 'CHANGE_MAIL_STATUS',
  DELETE_MAILS_SUCCESS: 'DELETE_MAILS_SUCCESS',
  SELECT_MAIL: 'SELECT_MAIL',
  CLEAR_SELECTED_MAILS: 'CLEAR_SELECTED_MAILS',
  CHANGE_STATUS: 'CHANGE_STATUS',
  CHANGE_MAILS_STATUS_SUCCESS: 'CHANGE_MAILS_STATUS_SUCCESS',
  CHANGE_SEARCH: 'CHANGE_SEARCH'
}

export default types;